module.exports = {
  SICK: 'SICK',
  VACATION: 'VACATION',
  DAY_OFF: 'DAY_OFF',
  UNPAID_LEAVE: 'UNPAID_LEAVE',
  PATERNITY_LEAVE: 'PATERNITY_LEAVE',
  BEREAVEMENT_LEAVE: 'BEREAVEMENT_LEAVE',
  MARRIAGE_LEAVE: 'MARRIAGE_LEAVE',
}